eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081

  data:
    mongodb:
      uri: mongodb+srv://admin:${spring.application.mongo-password}@bankingcluster.ayhvgpk.mongodb.net/${spring.application.database}?retryWrites=true&w=majority&appName=bankingCluster

  cloud:
    gateway:
      server:
        webflux: # ← new key structure
          routes:
            - id: user-service
              uri: http://host.docker.internal:8086
              predicates:
                - Path=/api/users/**,/api/security-details/**

            - id: auth-service-external
              uri: http://host.docker.internal:8087
              predicates:
                - Path=/api/auth/**

            - id: auth-service-internal
              uri: http://host.docker.internal:8087
              predicates:
                - Path=/internal/api/auth/**

            - id: admin-service
              uri: http://host.docker.internal:8089
              predicates:
                - Path=/api/admin/**

        # Add other microservice routes as needed
app:
  config:
    keycloak:
      url: http://localhost:5433
      realm: event-based-banking-application
      token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
      jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
