eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081

  data:
    mongodb:
      uri: mongodb+srv://admin:${spring.application.mongo-password}@bankingcluster.ayhvgpk.mongodb.net/${spring.application.database}?retryWrites=true&w=majority&appName=bankingCluster
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redisbanking}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://arya-banking-user-service
          predicates:
            - Path=/api/users/**,/api/security-details/**

        - id: auth-service-external
          uri: lb://arya-banking-auth-service
          predicates:
            - Path=/api/auth/**

        - id: auth-service-internal
          uri: lb://arya-banking-auth-service
          predicates:
            - Path=/internal/api/auth/**

        - id: admin-service
          uri: lb://arya-banking-admin-service
          predicates:
            - Path=/api/admin/**

        - id: admin-service-api-docs
          uri: lb://arya-banking-admin-service
          predicates:
            - Path=/admin-service/v3/api-docs
          filters:
            - RewritePath=/admin-service/v3/api-docs, /v3/api-docs

        - id: auth-service-api-docs
          uri: lb://arya-banking-auth-service
          predicates:
            - Path=/auth-service/v3/api-docs
          filters:
            - RewritePath=/auth-service/v3/api-docs, /v3/api-docs

        - id: user-service-api-docs
          uri: lb://arya-banking-user-service
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - RewritePath=/user-service/v3/api-docs, /v3/api-docs
app:
  config:
    keycloak:
      url: http://localhost:5433
      realm: event-based-banking-application
      token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
      jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
